spring.application.name=backend

## Importo il file .env indicando a Spring di leggerlo come file di properties
spring.config.import=optional:file:.env[.properties]

# database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Hibernate properties
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect

# Hibernate ddl auto
#spring.jpa.hibernate.ddl-auto = create  
# spring.jpa.hibernate.ddl-auto = create-drop  
# spring.jpa.hibernate.ddl-auto = validate  
spring.jpa.hibernate.ddl-auto = update

# spring.jpa.generate-ddl=false 

#definizione porta
server.port=8080

